# Generated by Django 4.2.30 on 2026-07-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='icono',
        ),
    ]
